#ifndef PID_GAINS_H
#define PID_GAINS_H

/* Auto-generated by python/codegen.py via Ziegler-Nichols tuning.
   Do NOT hand-edit — re-run `python3 python/codegen.py` to regenerate. */
#define PID_KP         2.5f
#define PID_KI         0.1f
#define PID_KD         0.05f
#define PID_DT         0.001f
#define PID_CLAMP_MIN  -200.0f
#define PID_CLAMP_MAX   200.0f

#endif /* PID_GAINS_H */
