#!/usr/bin/env python3
"""Generate include/pid_gains.h from BLDC model Ziegler-Nichols tuning.

Usage:
    python3 python/codegen.py --output include/pid_gains.h
"""
from __future__ import annotations
import argparse
import sys
import os

# Allow running from repo root
sys.path.insert(0, os.path.dirname(__file__))
from bldc_model import BldcModel
from zn_tuner import tune_pid

TEMPLATE = """\
#ifndef PID_GAINS_H
#define PID_GAINS_H

/* Auto-generated by python/codegen.py via Ziegler-Nichols tuning.
   Do NOT hand-edit — re-run `python3 python/codegen.py` to regenerate. */
#define PID_KP         {Kp:.6g}f
#define PID_KI         {Ki:.6g}f
#define PID_KD         {Kd:.6g}f
#define PID_DT         {dt:.6g}f
#define PID_CLAMP_MIN  {clamp_min:.1f}f
#define PID_CLAMP_MAX  {clamp_max:.1f}f

#endif /* PID_GAINS_H */
"""


def generate(output_path: str) -> None:
    model = BldcModel()
    gains = tune_pid(model)
    content = TEMPLATE.format(
        Kp=gains.Kp, Ki=gains.Ki, Kd=gains.Kd, dt=gains.dt,
        clamp_min=gains.clamp_min, clamp_max=gains.clamp_max,
    )
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Generated {output_path}: Kp={gains.Kp:.4f} Ki={gains.Ki:.4f} Kd={gains.Kd:.4f}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="PID gains code generator")
    parser.add_argument("--output", default="include/pid_gains.h")
    args = parser.parse_args()
    generate(args.output)
